reviewing:
  period: 2023 to present
  journals:
    - Operations Research Forum (Springer)
    - IEEE Transactions on Industrial Informatics
    - Journal of Process Control
other:
  - period: 2015 to 2021
    text: Contributor to program accreditation activities for the Industrial and Production Engineering discipline, Ahsanullah University of Science and Technology
affiliations:
  - name: Institute for Operations Research and the Management Sciences (INFORMS)
    period: 2022 to 2023, 2026 to 2027
